### ISSUE TITLE
Add scooze_id to Cards

### ISSUE THREAD

**Issue by iambroadband** [arcavios/scooze#192]
### Description
As part of the convert Deck<>DeckModel issue #70 , we discovered that it would not be possible to lookup cards in the database unless the Card class had some notion of scooze_id. We are adding it here. And to future proof for Tournaments needing to look up decks by id, we are adding it to Deck as well.

**Comment by fjork3** [comment]
Two potential options for making sure card objects that get added directly to DB have an ID assigned:
- our Python `add_card` wrapper mutates the Card object it was passed with the newly created `scooze_id`
- we return the full model of the object added (which includes a `scooze_id`), rather than just an ObjectId; users who want to use that ID further down the line would be expected to store that themselves

**Comment by iambroadband** [comment]
Closed with #193
